name: 'GitHub Release'

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            [README](https://github.com/dayantrivani/ChatGPT-Next-Web/blob/release/README.md)